`timescale 1ns / 1ps
/*
----------------------------------------------------------------------------------
-- Company: NUS	
-- Engineer: (c) Rajesh Panicker  
-- 
-- Create Date: 09/22/2020 06:49:10 PM
-- Module Name: Decoder
-- Project Name: CG3207 Project
-- Target Devices: Nexys 4 / Basys 3
-- Tool Versions: Vivado 2019.2
-- Description: RISC-V Processor Decoder Module
-- 
-- Dependencies: NIL
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments: Interface and implementation can be modified.
-- 
----------------------------------------------------------------------------------

----------------------------------------------------------------------------------
--	License terms :
--	You are free to use this code as long as you
--		(i) DO NOT post it on any public repository;
--		(ii) use it only for educational purposes;
--		(iii) accept the responsibility to ensure that your implementation does not violate anyone's intellectual property.
--		(iv) accept that the program is provided "as is" without warranty of any kind or assurance regarding its suitability for any particular purpose;
--		(v) send an email to rajesh<dot>panicker<at>ieee.org briefly mentioning its use (except when used for the course CG3207 at the National University of Singapore);
--		(vi) retain this notice in this file as well as any files derived from this.
----------------------------------------------------------------------------------
*/

module Decoder(
    input [6:0] Opcode ,    // Instr[6:0]
    input [2:0] Funct3 ,    // Instr[14:12]
    input [6:0] Funct7 ,    // Instr[31:25]
    output reg [1:0] PCS,		// 00 for non-control, 01 for conditional branch, 10 for jal, 11 for jalr
    output reg RegWrite,		// Asserted only by instructions which write to register file (load, auipc, lui, DPImm, DPReg);
    output reg MemWrite,		// Asserted only by store (sw)
    output reg [1:0] MemtoReg,		// Asserted only by load (lw), got extended to handle the output of Mcycle
    output reg [1:0] ALUSrcA, 	// Needed for lui, auipic. Refer to the microarchitecture for its use. Uncomment wire and port map in RV.v as well
    output reg [1:0] ALUSrcB,		// Asserted by all instructions which use an immediate (load, store, lui, auipc, DPImm). Needs to be expanded to a 2-bit signal to support link functionality for jal, jalr. Change wire width in RV.v as well
    output reg [2:0] ImmSrc, 	// 000 for U, 010 for UJ, 011 for I, 110 for S, 111 for SB.
    output reg [3:0] ALUControl,	// 0000 for add, 0001 for sub, 1110 for and, 1100 for or, 0010 for sll, 1010 for srl, 1011 for sra, 0001 for branch, 0000 for all others.
    					// Note that the most significant 3 bits are Funct3 for all DP instrns. LSB is the same as Funct[5] for DPReg type and DPImm_shifts. For other DPImms, Funct[5] is 0.
    					// It is the same as sub for branches, and add for all others not mentioned in the line above.
    output reg [1:0] MCycleOp, // // Multi-cycle Operation. "00" for signed multiplication(mul, and mulh), "01" for unsigned multiplication(mulhu), "10" for signed division, "11" for unsigned division. Generated by Control unit
    output reg Start // Multi-cycle Enable. The control unit should assert this when an instruction with a multi-cycle operation is detected.
    ); 
// Change wire to reg if assigned inside a procedural (always) block. However, where it is easy enough, use assign instead of always.
// A 2-1 multiplexing can be done easily using an assign with a ternary operator
// For multiplexing with number of inputs > 2, a case construct within an always block is a natural fit. DO NOT to use nested ternary assignment operator as it hampers the readability of your code.

    // todo: Implement Decoder here
	// this circuit is totally combinational.

    always @(*) begin
        case(Opcode)
            7'h33: begin // DP Reg
                PCS = 2'b00;
                RegWrite = 1'b1;
                MemWrite = 1'b0;
                MemtoReg = 2'b00;
                ALUSrcA = 2'bX0; // x0
                ALUSrcB = 2'bX0; // x0
                ImmSrc = 3'bXXX; // xxx
                ALUControl = {Funct3, Funct7[5]};
                MCycleOp = 2'bxx; // xx
                Start = 1'b0; 
                if (Funct7[0] == 1'b1) begin // multiply and divide
                    Start = 1'b1; 
                    case(Funct3)
                        3'h0: begin // mul
                            MCycleOp = 2'b00;
                            MemtoReg = 2'b11;
                        end
                        3'h1: begin // mulh
                            MCycleOp = 2'b00;
                            MemtoReg = 2'b01;
                        end
                        3'h3: begin // mulhu
                            MCycleOp = 2'b01;
                            MemtoReg = 2'b01;
                        end
                        3'h4: begin // div
                            MCycleOp = 2'b10;
                            MemtoReg = 2'b11;
                        end
                        3'h5: begin // divu
                            MCycleOp = 2'b11;
                            MemtoReg = 2'b11;
                        end
                        3'h6: begin // rem
                            MCycleOp = 2'b10;
                            MemtoReg = 2'b01;
                        end
                        3'h7: begin // remu
                            MCycleOp = 2'b11;
                            MemtoReg = 2'b01;
                        end
                        default: begin 
                            MCycleOp = 2'bxx;
                            MemtoReg = 2'bxx;
                        end
                    endcase
                end
            end
            7'h13: begin // DP Immediate
                PCS = 2'b00;
                RegWrite = 1'b1;
                MemWrite = 1'b0;
                MemtoReg = 2'b00;
                ALUSrcA = 2'bX0; // x0
                ALUSrcB = 2'b11;
                ImmSrc = 3'b011;
                if (Funct3 == 3'h5) begin
                    ALUControl = {Funct3, Funct7[5]}; // {Funct3, Immediate[10]}
                end
                else begin
                    ALUControl = {Funct3, 1'b0}; // {Funct3, 1'b0}
                end
                MCycleOp = 2'bxx; // xx
                Start = 1'b0; 
            end
            7'h03: begin // load
                PCS = 2'b00;
                RegWrite = 1'b1;
                MemWrite = 1'b0;
                MemtoReg = 2'b10;
                ALUSrcA = 2'bX0; // x0
                ALUSrcB = 2'b11;
                ImmSrc = 3'b011;
                ALUControl = 4'b0000;
                MCycleOp = 2'bxx; // xx
                Start = 1'b0; 
            end
            7'h23: begin // store
                PCS = 2'b00;
                RegWrite = 1'b0;
                MemWrite = 1'b1;
                MemtoReg = 2'bXX; // xx
                ALUSrcA = 2'bX0; // x0
                ALUSrcB = 2'b11;
                ImmSrc = 3'b110;
                ALUControl = 4'b0000;
                MCycleOp = 2'bxx; // xx
                Start = 1'b0; 
            end
            7'h63: begin // branch
                PCS = 2'b01;
                RegWrite = 1'b0;
                MemWrite = 1'b0;
                MemtoReg = 2'bXX; // xx
                ALUSrcA = 2'bX0; // x0
                ALUSrcB = 2'bX0; // x0
                ImmSrc = 3'b111;
                ALUControl = 4'b0001;
                MCycleOp = 2'bxx; // xx
                Start = 1'b0; 
            end
            7'h6F: begin // jal
                PCS = 2'b10;
                RegWrite = 1'b1;
                MemWrite = 1'b0;
                MemtoReg = 2'b00;
                ALUSrcA = 2'b11;
                ALUSrcB = 2'b01;
                ImmSrc = 3'b010;
                ALUControl = 4'b0000;
                MCycleOp = 2'bxx; // xx
                Start = 1'b0; 
            end
            7'h17: begin // auipc
                PCS = 2'b00;
                RegWrite = 1'b1;
                MemWrite = 1'b0;
                MemtoReg = 2'b00;
                ALUSrcA = 2'b11;
                ALUSrcB = 2'b11;
                ImmSrc = 3'b000;
                ALUControl = 4'b0000;
                MCycleOp = 2'bxx; // xx
                Start = 1'b0; 
            end
            7'h37: begin // lui
                PCS = 2'b00;
                RegWrite = 1'b1;
                MemWrite = 1'b0;
                MemtoReg = 2'b00;
                ALUSrcA = 2'b01;
                ALUSrcB = 2'b11;
                ImmSrc = 3'b000;
                ALUControl = 4'b0000;
                MCycleOp = 2'bxx; // xx
                Start = 1'b0; 
            end
            7'h67: begin // jalr
                PCS = 2'b11;
                RegWrite = 1'b1;
                MemWrite = 1'b0;
                MemtoReg = 2'b00;
                ALUSrcA = 2'b11;
                ALUSrcB = 2'b01;
                ImmSrc = 3'b011;
                ALUControl = 4'b0000;
                MCycleOp = 2'bxx; // xx
                Start = 1'b0; 
            end
            default: begin
                PCS = 2'bx;
                RegWrite = 1'bx;
                MemWrite = 1'bx;
                MemtoReg = 1'bx;
                ALUSrcA = 2'bx;
                ALUSrcB = 2'bx;
                ImmSrc = 3'bx;
                ALUControl = 4'bx;
                MCycleOp = 2'bxx; // xx
                Start = 1'b0; 
            end
        endcase
    end

endmodule
